### ISSUE TITLE
Can you implement format parameter of google api

### ISSUE THREAD

**Issue by Andicot** [aurawindsurfing/google-translate#1]
Thank's, is useful set format to text to preserve newline in text string.

**Comment by aurawindsurfing** [comment]
Can you show an example please or maybe do a pull request?

**Comment by Andicot** [comment]
Edited Translator.php

[Translator.php.zip](https://github.com/aurawindsurfing/google-translate/files/2351298/Translator.php.zip)

**Comment by aurawindsurfing** [comment]
pull request please
